import { webkit, devices } from 'playwright'
const base = process.argv[2]
const out = '/private/tmp/claude-501/-Users-clarencegomis-Downloads-project/d3da9c56-ff31-40a9-a2b8-7c70b3ab184a/scratchpad'
const browser = await webkit.launch()
const context = await browser.newContext({ ...devices['iPhone 14 Pro'] })
const page = await context.newPage()
await page.goto(base + '/', { waitUntil: 'networkidle' })
await page.fill('#loginEmail', 'diagnostic.temporaire@nira-ia.com')
await page.fill('#loginPassword', 'DiagnosticRelay2026!')
await page.click('#loginForm button[type="submit"]')
await page.waitForTimeout(4500)
// fenêtre d'administration des comptes
await page.click('#openMembers'); await page.waitForTimeout(2500)
await page.screenshot({ path: `${out}/m-d1-equipe.png` })
await page.keyboard.press('Escape')
// nouveau projet
await page.click('#newProjectTop'); await page.waitForTimeout(700)
await page.screenshot({ path: `${out}/m-d2-nouveau-projet.png` })
await page.keyboard.press('Escape')

await page.goto(base + '/workspace.html?project=perfectserve', { waitUntil: 'networkidle' })
await page.waitForTimeout(6000)
await page.click('[data-view="calendar"]'); await page.waitForTimeout(1500)
await page.screenshot({ path: `${out}/m-d3-agenda.png` })
await page.click('[data-view="map"]'); await page.waitForTimeout(1200)
await page.screenshot({ path: `${out}/m-d4-carto.png` })
await page.click('[data-view="interviews"]'); await page.waitForTimeout(900)
await page.click('[data-tab="collaborators"]'); await page.waitForTimeout(900)
await page.click('#newCollaborator'); await page.waitForTimeout(700)
await page.screenshot({ path: `${out}/m-d5-collaborateur.png` })
await page.keyboard.press('Escape')
await page.click('[data-tab="interviews"]'); await page.waitForTimeout(600)
await page.click('#interviewList .interview-row'); await page.waitForTimeout(1200)
await page.screenshot({ path: `${out}/m-d6-synthese.png` })
const debord = await page.evaluate(`document.documentElement.scrollWidth - window.innerWidth`)
console.log('débordement :', debord)
await browser.close()
